package com.ruinscraft.chip;

public enum Modification {
	
	ENTITY_INVULNERABLE,
	ENTITY_GLOWING,
	ENTITY_CUSTOM_NAME_TOO_LONG,
	ENTITY_CUSTOM_NAME_VISIBLE,
	ENTITY_ARMOR_STAND_SMALL,
	ENTITY_ARMOR_STAND_VISIBLE,
	ENTITY_ARMOR_STAND_BASE_PLATE,
	
	ITEMSTACK_ENCHANTMENT_TOO_HIGH,
	ITEMSTACK_ENCHANTMENT_TOO_LOW,
	ITEMSTACK_ENCHANTMENT_NOT_COMPATIBLE,
	ITEMSTACK_FIREWORK_NOT_CRAFTABLE,
	ITEMSTACK_META_CUSTOM_LORE,
	ITEMSTACK_META_UNBREAKABLE,
	ITEMSTACK_META_COLORED_NAME,
	ITEMSTACK_META_COLORED_LORE,
	ITEMSTACK_META_NAME_TOO_LONG,
	ITEMSTACK_META_LORE_TOO_LONG,
	ITEMSTACK_POTION_CUSTOM,
	
}
