###############################################
#  CHIP Configuration File                    #
#  https://www.spigotmc.org/resources/53809/  #
###############################################

# Whether or not OPs will bypass the checks (players with permission chip.bypass will bypass)
ops_bypass_checks: false
# Removes the item if it is deemed to have modifications
# If false, the item will simply be stripped of the modifications
remove_item: false
# Removes the entity if it is deemed to have modifications
# If false, the entity will simply be stripped of the modifications
remove_entity: false
book_forgery_prevention:
  # Whether or not to use the book forgery protection (alerts users if books have modified authors or were not signed on the server)
  enable: false
  # Only valid when enable is set to true
  # This will backup your secret key to the world directories in case you delete your plugins directory
  # Remember if you lose your secret, all books will be considered forged
  backup_signed_book_secret_to_world_directories: true
  # Only valid when enable is set to true
  alert_if_forged_action_bar: true
  # Only valid when enable is set to true
  alert_if_forged_chat: true
  # Only valid when enable is set to true
  alert_if_verified_action_bar: true
  # Only valid when enable is set to true
  alert_if_verified_chat: true
  # Disallow spreading of non verified books (players cannot drop them/move them to chests)
  prevent_distribution_of_non_verified_books: false
# Worlds you want CHIP to be checking
# If 'use' is set to false, CHIP will check all worlds
world_whitelist:
  use: false
  worlds:
    - 'world'
    - 'world_nether'
    - 'world_the_end'
# Whether or not notifications are enabled when modifications to items or entities are found
notifications:
  chat: false
  console: true
# Defines which modifications are permitted on this server
allowed_modifications:
  enchantments:
    # Allow above normal enchantments on items?
    above_normal_enchants: false
    # Allow below normal enchantments on items?
    below_normal_enchants: false
    # Allow conflicting enchantments on items?
    conflicting_enchants: false
  fireworks:
    # Allow fireworks which would be impossible to craft with a Crafting Table?
    non_craftable_fireworks: false
  item_meta:
    # Allow items to have a custom lore set? (Useful for other plugins)
    custom_lore: true
    # Allow items to be unbreakable?
    unbreakable_items: false
    # Allow item names to be colorized?
    colored_custom_names: true
    # Allow item lore to be colorized?
    colored_custom_lore: true
  entities:
    # Allow invulnerable entities?
    invulnerable: false
    # Allow glowing entities?
    glowing: false
    # Allow visible names above entities?
    custom_name_visible: false
    armor_stands:
      # Allow small armor stands?
      small: true
      # Allow visible armor stands?
      visible: true
      # Allow base plate on armor stands?
      base_plate: true
      # Allow arms on armor stands?
      arms: true
  nbt:
    # Allow NBT attribute modifications?
    attribute_modifiers: false
    # Allow custom potions?
    custom_potions: false
    # Allow a death loot table (custom drops on death)?
    death_loot_table: false
    # Allow larger slimes, etc?
    size: false
    # Allow a larger explosion radius?
    explosion_radius: false
    # Allow extra tile entity data?
    tile_entity_data: false
    # Allow block entity data (chests with items predefined, etc)?
    block_entity_tag: false
# Maximum custom name length of items
max_custom_name_length: 35
# Maximum custom lore length per line of items
max_custom_lore_length_per_line: 64
# Ignore head item names (conflicts with a lot of head plugins)? 
ignore_head_names: true
# Ignore head item lores (conflicts with a lot of head plugins)?
ignore_head_lores: true