# Checks for hacked items in blocks which have inventories (chests, furnaces, etc) on chunk load
# Causes lag and experimental, not recommended, may improve in the future
chunk_load_inspection: false

# Completely removes an item deemed modified
# Normal behavior typically just strips modified features from the item
remove_item: false

# Completely removes an entity deemed modified
# Normal behavior typically just strips modified features from the entity
remove_entity: false

# Whether or not OPs bypass modified item checks
ops_bypass_checks: false

# Notifications about found modified items/entities
notifications:
  # Sent to players with chip.notifiy
  chat: false
  console: true

allowed_modifications:
  enchantments:
    above_normal_enchants: false
    below_normal_enchants: false
    conflicting_enchants: false
  fireworks:
    non_craftable_fireworks: false
  item_meta:
    custom_lore: true
    unbreakable_items: false
    colored_custom_names: true
    colored_custom_lore: true
  entities:
    invulnerable: false
    glowing: false
    custom_name_visible: false
    armor_stands:
      small: false
      visible: false
      base_plate: false
  nbt:
    attribute_modifiers: false
    custom_potions: false
    death_loot_table: false
    size: false
    entity_tag: false
    explosion_radius: false
    tile_entity_data: false

# Default max length is 35 when renaming items with anvil
max_custom_name_length: 35
max_custom_lore_length_per_line: 64

# Use this if you use a heads spawning plugin that creates custom names and lore for heads
ignore_head_names_and_lore: true

env_blocking:
  # This is useful for finding large sources of lag
  notify_console_when_cancelled: false
  water_flow: false
  lava_flow: false
  tnt_update: false
  sponge_update: false