name: ${name}
version: ${version}
main: ${mainClass}
authors: [royalkingkb, Concurrence]

depend: [ProtocolLib]

commands:
  chip:
    permission: chip.command.info
  chip reload:
    permission: chip.command.reload