name: ${name}
version: ${version}
main: ${mainClass}
authors: [royalkingkb, Concurrence]

depend: [ProtocolLib]

commands:
  chip:
    description: Information about CHIP
    permission: chip.command.info
  chip reload:
    description: Reload the CHIP configuration file
    permission: chip.command.reload
  verifybook:
    description: Verify a written book
  